ISP_PROG  = usbtinyisp
#ISP_PORT  = /dev/ugen1.00
ISP_PORT  = /dev/ttyU0
BOARD_TAG = leonardo
#BOARD_TAG = leonardoeth
#ARDUINO_LIBS = Wire SoftwareSerial
ARDUINO_LIBS = Wire lcd1x9-master SoftwareSerial
include /usr/local/share/arduino-makefile/Arduino.mk
chrysalide:
